# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 266437cf8475e55dc794e6493b16b284e37a939e7046fe3c788befbf0aaca0ec381d16940e3bd72c1f75ea094df1fec5f239a1cc2b4381eaf20ce22c23ec5b40

test:
  secret_key_base: 57809fc7ab4875061dc2378584208ef7903a492073c49471e7ec51373f85d2369adf62c35cf515a66916929bec1e60db8d15bd52a682896d023f33df03bc3dc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
